### We change the signal by trading the deviations of the 30-day moving average of the markets spot rates to the Real Exchange Rates we computed

We assume the following theoretical value of the interest rate : $St = P(usd)/P(f) * GDP(f)/GDP(usd)$

In [11]:
import pandas as pd

#Importing PPP data 
from data import PPP_import

df_PPP = PPP_import().dropna() #We remove any date exhibiting Nan, we'll need to relax this hyptohesis

#Importing GDP data
df_GDP = pd.read_csv("/Users/hirecheariles/Documents/Cours/Master Finance/ARP/Data/GDPPPPData.csv", sep=";", skiprows=4)

df_GDP.drop(["Indicator Name", "Indicator Code", "2025", "Unnamed: 70"], axis=1, inplace = True)

df_GDP = df_GDP.loc[:, ["Country Code"]].join(df_GDP.loc[:, "1990":]).set_index("Country Code").T #Only keeping relevant columns
US_GDP = df_GDP.loc[:, "USA"] #Storing the reference GDP
df_GDP = df_GDP.loc[:, ["AUS", "BRA", "CAN", "CHL", "EMU", "HUN", "IND", "IDN", "ISR", "JPN", "MEX", "NZL", "NOR", "POL", "RUS", "SGP", "ZAF", "SWE", "CHE", "CZE", "GBR"]]

GDPmapping = pd.DataFrame(index = ["AUS", "BRA", "CAN", "CHL", "EMU", "HUN", "IND", "IDN", "ISR", "JPN", "MEX", "NZL", "NOR", "POL", "RUS", "SGP", "ZAF", "SWE", "CHE", "CZE", "GBR"],
                       data = ['AUD', 'BRL', 'CAD', 'CLP', 'EUR', 'HUF', "INR", "IDR", "ILS", "JPY", "MXN", "NZD", "NOK", "PLN", "RUB", "SGD", "ZAR", "SEK", "CHF", "CZK", "GBP"]).to_dict()[0]

df_GDP = df_GDP.rename(columns=GDPmapping) #Right names to the right columns
df_GDP = df_GDP.div(US_GDP, axis=0) #we compute the ratio GDP(f)/GDP(usd)
df_GDP.index = pd.to_datetime(df_GDP.index, format="%Y") #changing to datetime

df_GDP.head()

Country Code,AUD,BRL,CAD,CLP,EUR,HUF,INR,IDR,ILS,JPY,...,NZD,NOK,PLN,RUB,SGD,ZAR,SEK,CHF,CZK,GBP
1990-01-01,0.049753,0.167271,0.093924,0.010015,0.901209,0.015951,0.175802,0.093670,0.012286,0.412311,...,0.008271,0.013131,0.039529,0.199201,0.012169,0.043606,0.029219,0.032052,0.022264,0.158456
1991-01-01,0.050069,0.169180,0.092059,0.010839,0.922185,0.014070,0.177852,0.100253,0.013249,0.427301,...,0.008230,0.013551,0.036796,0.189353,0.012997,0.043209,0.028915,0.031793,0.019700,0.156578
1992-01-01,0.048945,0.162535,0.089719,0.011846,0.899414,0.013174,0.181219,0.103134,0.013791,0.416479,...,0.008058,0.013557,0.036438,0.156331,0.013389,0.040847,0.027608,0.030698,0.018933,0.153208
1993-01-01,0.049420,0.165972,0.089637,0.012462,0.868767,0.012748,0.184745,0.106892,0.013975,0.403464,...,0.008281,0.013570,0.036788,0.138956,0.014523,0.040243,0.026313,0.029838,0.018437,0.154310
1994-01-01,0.049292,0.168882,0.090037,0.012722,0.855950,0.012615,0.189415,0.110500,0.014431,0.392040,...,0.008498,0.013704,0.037235,0.116784,0.015510,0.039922,0.026310,0.029047,0.018239,0.155681

We interpret it as : in 1990, we should rationate the US price level by a scale of 0.9012 to compare it to the EU taking the Penn effect into account.

In [12]:
#Building the theoretical exchange rate

df_PPP

CURRENCY,AUD,BRL,CAD,CHF,CLP,CZK,EUR,GBP,HUF,IDR,...,INR,JPY,MXN,NOK,NZD,PLN,RUB,SEK,SGD,ZAR
TIME_PERIOD,,,,,,,,,,,,,,,,,,,,,
1995-01-01,1.310302,0.539108,1.209018,1.922675,278.809422,11.152963,0.875512,0.712913,61.472314,510.861176,...,7.952394,174.247214,3.006706,9.069835,1.466538,1.163351,1.715170,9.348993,1.006373,2.034084
1996-01-01,1.313356,0.627126,1.207172,1.887199,278.469518,12.071769,0.882957,0.712844,73.855397,545.204682,...,8.400987,170.351722,3.740912,8.973256,1.472926,1.350763,2.455975,9.245636,1.003165,2.157757
1997-01-01,1.307709,0.664144,1.200327,1.844032,282.866287,12.902515,0.867835,0.708637,87.377995,603.340128,...,8.793420,168.308686,4.329651,9.055966,1.451281,1.512912,2.778421,9.329317,0.996859,2.293788
1998-01-01,1.300774,0.689104,1.184866,1.827602,281.901592,13.986306,0.862638,0.720671,97.816595,1045.728708,...,9.392232,166.393737,4.954420,9.311803,1.449162,1.654902,3.258399,9.395336,0.972681,2.451477
1999-01-01,1.296950,0.733919,1.190810,1.802836,284.049363,14.229350,0.865406,0.725819,104.545883,1177.158453,...,9.545346,162.035740,5.633670,9.283739,1.434660,1.737656,5.539641,9.305900,0.924793,2.583792
2000-01-01,1.312261,0.757895,1.228197,1.788660,290.423477,14.327536,0.860905,0.704372,110.049076,1386.451585,...,9.674133,154.687365,6.078239,9.083460,1.444868,1.832541,7.301404,9.161129,0.939247,2.758554
2001-01-01,1.328086,0.802171,1.220053,1.768621,296.176351,14.323590,0.863926,0.694551,114.418570,1549.758991,...,9.765331,149.639771,6.329170,9.175302,1.473448,1.837258,8.322817,9.402445,0.901897,2.908249
2002-01-01,1.336490,0.867291,1.229333,1.709760,301.387054,14.458321,0.866973,0.689877,118.141282,1616.020707,...,9.973197,143.774205,6.553697,9.056730,1.468962,1.799795,9.273504,9.413655,0.880130,3.222802
2003-01-01,1.352188,0.970343,1.225777,1.715154,308.261553,14.177038,0.887261,0.695928,122.020996,1671.694194,...,10.158382,139.581668,6.647339,9.198149,1.495284,1.804595,9.866787,9.486667,0.847563,3.362538
2004-01-01,1.364774,1.018185,1.232603,1.691758,321.276779,14.427652,0.887427,0.687912,128.395563,1767.116880,...,10.458746,134.397629,6.998731,9.126614,1.505044,1.830239,11.556843,9.295284,0.858049,3.472334
2005-01-01,1.388356,1.060594,1.213644,1.686548,333.690000,14.562493,0.885317,0.707619,130.929945,1958.954190,...,10.710892,129.551955,7.126862,9.005204,1.535000,1.867595,12.736131,9.479182,0.847774,3.555209
2006-01-01,1.403300,1.098564,1.205262,1.598858,318.574722,14.417720,0.873627,0.696640,131.519432,2168.060922,...,11.263364,124.459311,7.130489,8.782047,1.482170,1.850859,12.618288,9.113464,0.837579,3.658012
2007-01-01,1.427068,1.138457,1.212177,1.531784,323.878962,14.256061,0.870130,0.709103,134.041265,2348.526121,...,11.727802,120.321744,7.367817,8.921240,1.506774,1.853583,13.984503,8.871216,0.863737,3.855196
2008-01-01,1.479073,1.214987,1.234390,1.493049,340.400833,13.916713,0.859163,0.701691,131.005355,2722.326442,...,12.563981,116.845814,7.469532,8.859281,1.490709,1.842243,14.341196,8.778986,0.835702,4.079247
2009-01-01,1.442855,1.295853,1.202269,1.470105,354.325885,13.631732,0.844917,0.709725,127.627536,2929.523479,...,13.366092,115.232346,7.493426,9.079448,1.472321,1.868238,14.016913,8.916357,0.855114,4.405462
2010-01-01,1.503481,1.388137,1.221672,1.466316,359.837020,13.675892,0.838156,0.702443,126.446576,3336.150750,...,14.595632,111.707557,7.727203,9.153830,1.496739,1.805328,15.821142,9.027189,0.854206,4.619309
2011-01-01,1.511052,1.473216,1.239904,1.397498,348.016847,13.345305,0.819884,0.706052,124.271836,3512.753906,...,15.549549,107.454281,7.673013,9.082736,1.485915,1.801424,18.443729,8.844042,0.846738,4.776628
2012-01-01,1.540115,1.609136,1.244607,1.354072,347.228507,13.297699,0.815034,0.701634,125.623608,3577.518924,...,16.135663,104.273972,7.858708,9.037085,1.495622,1.796168,19.568260,8.654768,0.845431,5.106045
2013-01-01,1.447123,1.708555,1.224000,1.312477,349.680536,12.785271,0.804317,0.695248,124.979432,3781.778237,...,17.288343,101.302673,7.884359,9.029349,1.445979,1.762045,19.505592,8.597681,0.857923,5.292065
2014-01-01,1.452489,1.824851,1.230358,1.281761,367.213907,12.703210,0.799567,0.698444,129.414974,4056.662662,...,18.300767,103.052076,8.045318,9.278458,1.440730,1.767142,20.998875,8.727131,0.862602,5.566095
2015-01-01,1.473691,2.005869,1.248042,1.235456,391.178861,12.937980,0.806367,0.692551,132.553510,4390.646497,...,19.115441,103.469437,8.327595,9.932516,1.478014,1.765116,23.562632,8.854383,0.877769,5.817177
2016-01-01,1.450156,2.155972,1.207045,1.201964,397.250703,12.576343,0.780419,0.688603,132.033797,4566.570668,...,19.744239,105.519502,8.446043,10.041900,1.441008,1.732843,24.192337,8.822586,0.876021,6.148418
2017-01-01,1.477553,2.209679,1.212304,1.187726,397.689401,12.424986,0.771767,0.684601,136.036522,4756.168945,...,20.455578,105.101901,8.913552,9.749830,1.430959,1.742879,24.124181,8.852247,0.883215,6.413337
2018-01-01,1.470403,2.197592,1.206524,1.178866,396.229413,12.371528,0.755250,0.687714,139.092451,4833.599121,...,20.474596,104.158636,9.276363,9.583999,1.470060,1.748426,24.542904,8.865881,0.867736,6.855415
2019-01-01,1.459253,2.216445,1.217860,1.133809,397.674408,12.097428,0.725699,0.669665,138.797140,4847.445313,...,20.239500,103.231509,9.528366,9.481152,1.436661,1.698557,23.934275,8.584015,0.854120,7.065221
2020-01-01,1.431163,2.264911,1.201689,1.104751,409.841785,12.150267,0.715094,0.653446,141.838435,4791.006836,...,20.319366,100.742048,9.814966,9.588324,1.422947,1.698184,23.145168,8.435616,0.834628,7.248924
2021-01-01,1.395724,2.379274,1.163492,1.056712,423.013786,12.561890,0.704553,0.668934,148.351175,4808.429199,...,20.727896,99.211289,10.060857,8.984704,1.463664,1.752789,23.685146,8.363733,0.811010,7.376138
2022-01-01,1.358727,2.411273,1.145083,0.986913,434.952253,12.476407,0.675316,0.633175,155.230128,4917.924692,...,20.489457,94.922107,9.922780,8.371497,1.433160,1.800275,26.129331,8.338151,0.869998,7.246109
2023-01-01,1.337468,2.447609,1.139727,0.999013,432.562121,12.576104,0.653349,0.660709,169.087073,4819.742243,...,20.290405,93.831737,9.751268,8.918221,1.461074,1.920474,27.239133,8.516641,0.797634,7.324720
2024-01-01,1.366527,2.487317,1.150472,0.972889,435.778953,12.823227,0.653895,0.664153,175.578089,4747.908576,...,20.421988,94.462599,9.916562,9.142143,1.463912,1.949414,29.062975,8.490485,0.804050,7.431913

The signal we want to build is the deviation to the theoretical exchange rate we've computed $signal = MovAvg(St_{market}, ndays) / St_{theoretical}$.  
We assume mean reversion and go long bottom 7 and short top 7 (3 for G10)

In [7]:
from data import spt_dol_import

mapping = {'AUSTDOL(ER)': "AUD", 'BRACRUZ(ER)':'BRL', 'CNDOLLR(ER)':'CAD', 'CHILPES(ER)':'CLP',
       'USEURSP(ER)':"EUR", 'HUNFORT(ER)':"HUF", 'INDRUPE(ER)':"INR", 'INDORUP(ER)':"IDR",
       'ISRSHEK(ER)':"ILS", 'JAPAYEN(ER)':"JPY", 'MEXPESO(ER)':"MXN", 'NZDOLLR(ER)':"NZD",
       'NORKRON(ER)':"NOK", 'POLZLOT(ER)':"PLN", 'CISRUBM(ER)':"RUB", 'SINGDOL(ER)':"SGD",
       'COMRAND(ER)':"ZAR", 'SWEKRON(ER)':"SEK", 'SWISSFR(ER)':"CHF", 'CZECHCM(ER)':"CZK", 'GBP(ER)':"GBP"}

spt_dol = spt_dol_import()
spt_dol_ma = spt_dol.rolling(30).mean().rename(mapping, axis=1) #The 30 days choice is tipically arbitrary, we might try other frames
spt_dol_ma[28:32]

,AUD,BRL,CAD,CLP,EUR,HUF,INR,IDR,ILS,JPY,...,NZD,NOK,PLN,RUB,SGD,ZAR,SEK,CHF,CZK,GBP
Code,,,,,,,,,,,,,,,,,,,,,
1998-02-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1998-02-11,0.662274,0.892272,0.694452,0.002211,1.080236,0.004846,0.025570,0.000109,0.279415,0.007807,...,0.581636,0.133276,0.283185,0.165933,0.580898,0.202703,0.124552,0.680041,0.028446,1.637320
1998-02-12,0.663158,0.892002,0.694341,0.002210,1.079947,0.004844,0.025579,0.000108,0.279256,0.007820,...,0.581786,0.133184,0.283138,0.165884,0.581306,0.202613,0.124480,0.680144,0.028453,1.637138
1998-02-13,0.663882,0.891701,0.694069,0.002209,1.079471,0.004841,0.025590,0.000106,0.279108,0.007834,...,0.581974,0.133063,0.283052,0.165842,0.581704,0.202534,0.124405,0.680186,0.028456,1.636983

In [8]:
#The median rebalancement try to avoid any noise from the beginning of a period
rebal_mth = spt_dol.index.to_series().groupby(spt_dol.index.to_period("M")).min() #Monthly rebalancement
rebal_qtr = spt_dol.index.to_series().groupby(spt_dol.index.to_period('Q')).min() #Quarterly rebalancement
rebal_qmed = spt_dol.index.to_series().groupby(spt_dol.index.to_period("Q")).median().dt.normalize() #Quarterly median date

In [ ]:
#We reindex the data to get a dataframe with observations at the right intervals
spt_mth = spt_dol.reindex(rebal_mth, method="ffill")
spt_qtr = spt_dol.reindex(rebal_qtr, method ="ffill")
spt_qmed = spt_dol.reindex(rebal_qmed, method="ffill")

df_PPPm = df_PPP.reindex(rebal_mth, method='ffill')
df_PPPq = df_PPP.reindex(rebal_qtr, method="ffill")
df_PPPqmed = df_PPP.reindex(rebal_qmed, method="ffill")

df_GDPm = df_GDP.reindex(rebal_mth, method="ffill")
df_GDPq = df_GDP.reindex(rebal_qtr, method="ffill")
df_GDPqmed = df_GDP.reindex(rebal_qmed, method="ffill")

We might aim to find a long term precise value by running a regression in sample of the form $St = ß0 + ßprices * P(USD)/P(f) + ßgdp * GDP(f)/GDP(usd)$ or $st = ß0 + ßprices * p(USD)-p(f) + ßgdp * gdp(f)-gdp(usd)$